#!/usr/bin/perl
print "Content-type: text/html\n\n";

@array = ("red", "blue", "orange", "white");
print "@array\n";

@array = qw(red blue orange white);
print "@array\n";

@numbers = (1,2,3,4,5);
print "@numbers\n";

@numbers = (1..20);
print "@numbers\n";

@array = (1) x 10;
print "@array\n";

@array = ("hello") x 10;
print "@array\n";

exit;
